name: Build

on:
  pull_request:
  push:

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        features: ["", --features ui]

    steps:
    - name: Install libsqlite3-dev
      if: contains(matrix.os, 'ubuntu') && !contains(matrix.features, 'bundle-sqlite')
      run: sudo apt-get update && sudo apt-get install libsqlite3-dev
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release ${{ matrix.features }}
